### ISSUE TITLE
Open post view not working when open_post_view_in set to panel

### ISSUE THREAD

**Issue by trixiegoff** [acarabott/supercollider-sublime#8]
Sublime Text Build 3153
OS: Windows 10

If I set the "open_post_view_in" option in preferences to "panel", I am unable to get any output to display at all.  I've tried manually opening the build output panel, but it still doesn't seem to display any output.

The other options work just fine as far as I can see.

I get the following output in the console when I try and choose Open Post View from the Tools/SuperCollider menu:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 782, in run_
    return self.run()
  File "SuperCollider in C:\Users\cotto\AppData\Roaming\Sublime Text 3\Installed Packages\SuperCollider ST3.sublime-package", line 555, in run
  File "SuperCollider in C:\Users\cotto\AppData\Roaming\Sublime Text 3\Installed Packages\SuperCollider ST3.sublime-package", line 318, in open_post_view
AttributeError: 'NoneType' object has no attribute 'run_command'
```

(Really love this package.  It was incredibly easy to get going, wonderful work- thank you!)

**Comment by acarabott** [comment]
Thanks for spotting this, I don't get the same error, but it is also not working on macOS. I hadn't tested this mode in a very long time and it looks like something changed within ST.

In your case it is trying to call `run_command` on the current window, but the current window is `None`. Do you get this error when you have a window open and focused?
